# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #6. dodaj fazę npm install =>
      - name: Install
        run: npm install

      #7. dodaj fazę unit test =>
      - name: unit-test
        run : npm run unit-tests
 
      #8. dodaj fazę integration tests =>
      - name: integration-test
        run : npm run integration-tests
 
      #9. dodaj fazę test report =>
      - name: Test Report unit
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: mocha Tests unit
          path: ./test-results.json
          reporter: mocha-json
 
      #11. dodaj fazę dependency check =>
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
         project: 'ms-starwars'
         path: '.'
         format: 'HTML'
         others: ''
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports

      #19. dodaj fazę sonar scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.TEST3 }}
          SONAR_TOKEN: ${{ secrets.TOKENSONAR }}
        with:
          args: >
            -Dsonar.organization=nomaduu
            -Dsonar.projectKey=Nomaduu_ms-starwars
          projectBaseDir: ./

      #23.dodaj fazy potrzebne do zbudowania obrazu dockerowego-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to JFrog
        uses: docker/login-action@v1
        with:
          registry: nomaduu.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
     
     #24. dodaj fazę budowania i promocji obrazu
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
         push: true
         tags: <nazwa organizacji>.jfrog.io/default-docker-local/test:latest
